name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build jekyll
        uses: actions/jekyll-build-pages@v1

      - name: Archive
        run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn
